### ISSUE TITLE
Is it possible to provide a pre-trained model？

### ISSUE THREAD

**Issue by phybrain** [wenwenyu/PICK-pytorch#1]

**Comment by wenwenyu** [comment]
@phybrain Thanks for your interest in our paper. Unfortunately, the original implementation is based on a private codebase that I don’t have access to the data and we are not able to share them to you. This repo is a reimplementation of PICK that you can used to train customized data by youself. Sorry!

**Comment by wenwenyu** [comment]
I am going to close this issue due to no response. Please feel free to reopen or create a new one if you have more questions.
