### ISSUE TITLE
请问train_samples_list.csv文件里面，为什么asdf、X00016469623各重复了四次？

### ISSUE THREAD

**Issue by yuzi1949** [wenwenyu/PICK-pytorch#10]
是因为训练集不够，增加数据考虑吗？谢谢！

**Comment by wenwenyu** [comment]
@yuzi1949 可能是我没写情况，data中提供的数据是一个例子，仅仅是为了展示训练和测试输入数据的格式。由于更多符合要求的数据在内部花费了人力进行里标注且目前无法访问，无法提供更多数据，请理解，谢谢。

**Comment by wenwenyu** [comment]
I am going to close this issue due to no response. Please feel free to reopen or create a new one if you have more questions.
