### ISSUE TITLE
请问下这个耗时大概多久

### ISSUE THREAD

**Issue by fxwfzsxyq** [wenwenyu/PICK-pytorch#11]

**Comment by wenwenyu** [comment]
@fxwfzsxyq 耗时是根据数据来定，在我们的实验中，文本框个数在100，文本最大长度50的设置下，8 卡V100， Batch Size 2*8，样本量在~2100的情况下，训练阶段每个epoch是耗时~35分钟。在测试阶段，CRF的Viterbi解码是比较耗时的步骤，其解码时间是和需要解码的文档长度成正比的。

**Comment by wenwenyu** [comment]
@fxwfzsxyq 耗时是根据数据来定，在我们的实验中，文本框个数在100，文本最大长度50的设置下，8 卡V100， Batch Size 2*8，样本量在2100的情况下，训练阶段每个epoch是耗时35分钟。在测试阶段，CRF的Viterbi解码是比较耗时的步骤，其解码时间是和需要解码的文档长度成正比的。

**Comment by wenwenyu** [comment]
I am going to close this issue due to no response. Please feel free to reopen or create a new one if you have more questions.

**Comment by yyx911216** [comment]
> @fxwfzsxyq 耗时是根据数据来定，在我们的实验中，文本框个数在100，文本最大长度50的设置下，8 卡V100， Batch Size 2*8，样本量在2100的情况下，训练阶段每个epoch是耗时35分钟。在测试阶段，CRF的Viterbi解码是比较耗时的步骤，其解码时间是和需要解码的文档长度成正比的。

您好，我发现训练时使用的GPU，验证的时候使用的CPU并且耗时较长，请问下有可能是**验证的时候CRF解码的时候使用的cpu**所以耗时较长吗？

**Comment by yyx911216** [comment]
我发现分布式运算时维特比解码速度很快，不到1秒：
![image](https://user-images.githubusercontent.com/13828098/98762976-e7fc9200-2413-11eb-96fb-c8f997ebda90.png)
但是单GPU运算时，维特比解码会放到CPU上去运行，速度大概40秒一张图片
![QQ截图20201111114941](https://user-images.githubusercontent.com/13828098/98763085-3742c280-2414-11eb-941c-51d7e7b3bb8a.jpg)
