### ISSUE TITLE
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59咋处理？

### ISSUE THREAD

**Issue by jingmouren** [wenwenyu/PICK-pytorch#14]
照着readme用的
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nnode=1 --node_rank=0 --nproc_per_node=4 \
--master_addr=127.0.0.1 --master_port=5555 \
train.py -c config.json --local_world_size 2
报标题错误
是config里也要作对应改动吗？如何改。谢谢

**Comment by wenwenyu** [comment]
@jingmouren 运行命令中`--nproc_per_node=4`改为`--nproc_per_node=2`

**Comment by jingmouren** [comment]
改了能运行了。
就是说nproc_per_node和nproc_per_node要一样？

**Comment by wenwenyu** [comment]
@jingmouren 推荐用法是`nproc_per_node`和`local_world_size `设置和`CUDA_VISIBLE_DEVICES`的数量一致
