### ISSUE TITLE
参数解释

### ISSUE THREAD

**Issue by FocueAI** [wenwenyu/PICK-pytorch#15]
能否对config.json中的配置参数进行解释？！

**Comment by wenwenyu** [comment]
@FocueAI 配置文件中的参数主要分为两大类，一类是和网络模型相关的参数，这类参数中的重要设置和含义在对应的类代码中有解释，第二类就是和运行训练时相关的参数，这类参数中比较重要的参数含义后续有空会加上解释。参数不懂的可以先去看看参数对应的代码，这样比较容易理解。
