### ISSUE TITLE
How to evaluate on SROIE2019?

### ISSUE THREAD

**Issue by tengerye** [wenwenyu/PICK-pytorch#18]
Hi, thank you for your great job. 

May I ask two questions please?
1. Did you use external data for SROIE 2019 competition? 
2. How did you evaluate on SROIE dataset?

**Comment by wenwenyu** [comment]
1. External data are not used but we build a lexicon for post-processing

2. At the training phase, we use span-based f1 metrics for logging and monitoring training process and saved bast top-k checkpoint. At the testing phase, we predict results and reconstruct to the final entity with constraint rules post-processing to correct the results then submit to the official evaluation website whose metric is entity-based f1.

**Comment by n0ct4li** [comment]
@wenwenyu Can you please give advices on your method for post processing for SROIE? Especially when you have multiple texts for same entity.
