### ISSUE TITLE
A question about test

### ISSUE THREAD

**Issue by courao** [wenwenyu/PICK-pytorch#2]
When testing, do we have to provide boxes and texts(scripts?) of the test images?

**Comment by wenwenyu** [comment]
@courao Surely. Usually, the boxes and texts (transcripts ) of documents are obtained by the OCR system including text detection and recognition. When you get transcripts and boxes, all you need to know is how to prepare the testing data correctly. You can refer to `data/README.md` file for detail about data format.

**Comment by wenwenyu** [comment]
I am going to close this issue due to no response. Please feel free to reopen or create a new one if you have more questions.
