### ISSUE TITLE
Questions of data example provided

### ISSUE THREAD

**Issue by tengerye** [wenwenyu/PICK-pytorch#20]
Hi, thank you for your great job. I have some questions about your data file in your repository. In `asdf.tsv` file,
in the 5th line `TAMAN DAYA,` is marked as `other`, shouldn't it be `address`? And there is no `total` tag in the label file.

Looking forward to your reply.

**Comment by wenwenyu** [comment]
`TAMAN DAYA,` should be `address` after check again. Sorry for typos. 

In the `asdf.tsv` file, line 28  is `total` tag.

This file's aim is to show how the correct format data should be prepared.
