### ISSUE TITLE
Did you try documents with variable layout? 

### ISSUE THREAD

**Issue by bravelywangexocr** [wenwenyu/PICK-pytorch#22]
Hi wenwenyu, 

Thanks this wonderful repo firstly. 

One quick question, have you tried the documents/forms with variable layout? 
I just wonder if GCN can still help and perform well if the (relative) positional features are not consistent. 

Thanks.

**Comment by wenwenyu** [comment]
Yes, We try it on the medical invoice having variable layout. Our experiments find that it can get the performance dropdown if we delete GCN compare with baseline method. GCN can help with extraction tasks even if the layout is not consistent.

**Comment by bravelywangexocr** [comment]
Get it, Thanks a lot!

**Comment by wenwenyu** [comment]
I am going to close this issue. Please feel free to reopen or create a new one if you have more questions.
