### ISSUE TITLE
Is it possible to get score in the form of probabilities?

### ISSUE THREAD

**Issue by Vcv85** [wenwenyu/PICK-pytorch#28]
Hi wenwenyu,

Is it possible to get score in the form of probabilities?

**Comment by wenwenyu** [comment]
Yes. `viterbi decode` will produce the best path and its scores. Details of the implementation of `viterbi decode` can refer to [viterbi_decode](https://github.com/wenwenyu/PICK-pytorch/blob/593c2644040da71bd04e6a9029c01464a5b83a8c/model/crf.py#L402).

**Comment by wenwenyu** [comment]
The `viterbi decode` will produce the best path and its scores. The output of scores can be regarded as probability. But it truly is the cost of transitions and logit. Details of the implementation of `viterbi decode` can refer to [viterbi_decode](https://github.com/wenwenyu/PICK-pytorch/blob/593c2644040da71bd04e6a9029c01464a5b83a8c/model/crf.py#L402).

**Comment by Vcv85** [comment]
Thank you. I will look
