### ISSUE TITLE
pretrained weights of docbank

### ISSUE THREAD

**Issue by kbrajwani** [wenwenyu/PICK-pytorch#33]
@wenwenyu  @tengerye 
Hey can you please upload pretrained weights of docbank dataset. Because this dataset is huge and i am using colab so i am not able to retrain this one. If you able to do it please it would be very helpful.

**Comment by tengerye** [comment]
@kbrajwani Hi, I am terribly sorry that I may not do that for now. The reason is it may violate the policy of my company.

**Comment by kbrajwani** [comment]
@tengerye not an issue. Thanks for such a good contribution.

**Comment by tengerye** [comment]
I will close the issue for now. Feel free to open it if there is any further question please.

**Comment by congphu2511995** [comment]
@tengerye 
Can i ask you the reuslt when you trained PICK on docbank dataset? Thank you.

**Comment by tengerye** [comment]
@congphu2511995 I am terribly sorry that I am not able to do that for now. However, I will leave you a message once I release the detailed result.
