### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by cloudfool** [wenwenyu/PICK-pytorch#36]
Hi, 

Does anyone met this problem during distributed training?

subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train.py', '--local_rank=3', '-c', 'config.json', '--local_world_size', '4']' returned non-zero exit status 1.

PLS give me some adivce, Tks

**Comment by huxiaotaostasy** [comment]
how to solve this?

**Comment by samanthawyf** [comment]
have you solved this and how?
