### ISSUE TITLE
Failed to converge with increased amount of BiLSTM layers

### ISSUE THREAD

**Issue by dbobrenko** [wenwenyu/PICK-pytorch#40]
Seems like PICK fails to converge with increased amount of BiLSTM layers.

Changed: **bilstm_kwargs** **"num_layers" from 2 to 4**.

With num_layers = 2 it converges in 6 epochs, once I tried layers = 4, it fails to converge in 42 epochs.
Is the problem in hyper-parameters?

**num_layers = 4, epoch = 42:**
![image](https://user-images.githubusercontent.com/17252809/94854419-879e2c00-0435-11eb-862b-d2e88853ab1d.png)

**num_layers = 2, epoch = 6 (Converged):**
![image](https://user-images.githubusercontent.com/17252809/94854497-a7cdeb00-0435-11eb-83e9-a93f25e25a4e.png)

**Comment by tengerye** [comment]
@dbobrenko Hi, did you try the latest version? We fixed a bug recently.

**Comment by dbobrenko** [comment]
@tengerye Hey TengQi, thanks for the response! Now it works
