### ISSUE TITLE
Testing with out-of-sample

### ISSUE THREAD

**Issue by karthikesh2020** [wenwenyu/PICK-pytorch#48]
While testing with out-of-sample images, i tried creating boxes_and_transcripts for new images using tesseract & prepare tsv files. but when i'm predicting output is not good as in-sample testing images.

kindly please let us know way to create bounding box files (tsv) for prediction for this model.

Also can we predict without tsv files?

Note: In tesseract i tried both WORD & TEXTLINE bounding boxes

**Comment by tengerye** [comment]
@karthikesh2020 What is the accuracy of Tesseract on your cases? A tool to recognize texts from images is necessary for our model.

**Comment by karthikesh2020** [comment]
Firstly Thankyou @tengerye for fast response.

Tesseract accuracy is good for extracting text information but the bounding box is either at word or line or para or block level.
For our current model, i think the bounding box info from tesseract is not good.

can you suggest any tool or model best for this current model

**Comment by tengerye** [comment]
@karthikesh2020 Yes, the model predicts on the texts (bounding boxes included) provided by OCR. Currently, the texts are either provided within the (open) dataset or from private tool (self-made). I suggest start with searching similar tools from big companies like Google, Facebook, etc.

All I can tell you is the OCR results make a huge difference.

**Comment by karthikesh2020** [comment]
Sure @tengerye, I will tryout with Tesseract OCR itself which is google's free version.

I labelled my dataset manually & extracted tsv file.

can i label as below way & train our model? 
i mean each word is assigned with a label like vendor_name etc..

![Screenshot 2020-10-13 at 7](https://user-images.githubusercontent.com/59757734/95868971-7e438680-0d88-11eb-9b04-57f9b3e1a919.png)

**Comment by tengerye** [comment]
@karthikesh2020 Yes, and if there are too many words on each page, use GPUs with large memory and set limit of the number of sentence to whatever you need.

**Comment by karthikesh2020** [comment]
Thank you so much @tengerye for the support. Will follow your resolution.

**Comment by ninjakx** [comment]
@karthikesh2020 : were you able to solve the problem?
