### ISSUE TITLE
boxes_and_transcripts label format

### ISSUE THREAD

**Issue by lmpan** [wenwenyu/PICK-pytorch#5]
boxes_and_transcripts 每张图片对应一个 .tsv标签
在说明文档中, 每个标签都是如下格式:
index, box_coordinates, transcripts, box_entity_types
在给的两个例子中, index标签有矛盾
X00016469623.tsv 标签中所有的index都是1
asdf.tsv 标签中index又是递增的, 对应的是行数
所以这个 index 到底是指标签对应图片在train_sample_list.csv 文件中的 index, 还是指行数？

**Comment by wenwenyu** [comment]
@lmpan index是指行数，给的例子中的index是重复的两个文件，copy的时候index没有跟着改动。实际使用时，只要index这个位置有数值就行，主要是读取每一行index后面的坐标、文本和类型值。

**Comment by lmpan** [comment]
谢谢你的回复!
