### ISSUE TITLE
Information extraction when bounding boxes are not present (prediction on unseen data)

### ISSUE THREAD

**Issue by AbhayPadda** [wenwenyu/PICK-pytorch#62]
Hi,

I was just exploring this model and found it useful for information extraction from scanned images. I need to know how can we make predictions on unlabelled data after we have trained the model?

By unlabelled data, I mean images where we do not have bounding box details.

Thanks in advance.

**Comment by AbhayPadda** [comment]
@wenwenyu It would be really great if you can help me with this.

**Comment by wenwenyu** [comment]
Hi, 

The bounding box and transcripts of unlabelled data can be predicted by the OCR system which means you need to train a text detection and recognition model. This is out of the scope of this paper.

Hope it can help you.

**Comment by AbhayPadda** [comment]
Thanks @wenwenyu for your reply.
