### ISSUE TITLE
What are the differences between 3 types of IoB tagging levels?

### ISSUE THREAD

**Issue by jorgerodriguezsj** [wenwenyu/PICK-pytorch#63]
There are 3 levels of IoB tagging: box_level, document_level and box_and_within_box_level. But I couldn`t see what is the most appropriate for my dataset. 

I have the entities in contiguous rows in the .tsv with the form B-tag , I-tag, I-tag ...

thanks

**Comment by ninjakx** [comment]
@jorgerodriguezsj : Did you find anything? I have the same question.

**Comment by jorgerodriguezsj** [comment]
@ninjakx Sorry for taking time to answer, I suppose you have already discovered the meaning of each one. The only one that is clear to me is the document_level that what it does is that the IOB tagging is performed on the entire document. The other two do it within the same box if there is only one category and the other if there is more than one category within the box. But of these last two I am not sure which one does what.
