### ISSUE TITLE
How can I use utf-8 encoded data?

### ISSUE THREAD

**Issue by jorgerodriguezsj** [wenwenyu/PICK-pytorch#64]
I am using text in Spanish, and when I test the dataset it does not return the Ñ correctly, I have searched through all the code and I cannot find where the line is to avoid this. Any help?

The output:

Address EGAOA
Address ESPAOA

It should be:

Address EGAÑA
Address ESPAÑA

Thanks

**Comment by cuongngm** [comment]
change your vocab in files utils/keys.txt based on your language and retrain model
