### ISSUE TITLE
UnionLayer好像写的有问题？

### ISSUE THREAD

**Issue by ChenCongGit** [wenwenyu/PICK-pytorch#75]
N个文本行的x和x_gcn不需要完全对齐吗？这里似乎只对x进行展开去padded的部分，但是x_gcn还是直接reshape(B,N*T,-1)，这样x_gcn的节点完全没法和x的文本行对齐了，而且后面x_gcn = x_gcn.reshape(B, N * T, -1)[:, :max_doc_seq_len, :]不太对啊。

**Comment by wenwenyu** [comment]
Hi, 谢谢提醒，此部分已修复。
