### ISSUE TITLE
Test.py output UTF-8

### ISSUE THREAD

**Issue by jorgerodriguezsj** [wenwenyu/PICK-pytorch#80]
I am using text in Spanish, and when I test the dataset it does not return the Ñ correctly, I have searched through all the code and I cannot find where the line is to avoid this. Any help?

The output:

Address EGAOA
Address ESPAOA

It should be:

Address EGAÑA
Address ESPAÑA

Thanks

**Comment by AtulKumar4** [comment]
@jorgerodriguezsj how did you solve it?

**Comment by jorgerodriguezsj** [comment]
Changing vocab in utils/keys.txt (Add Ñ or what you want based on your language) and retrain the model

**Comment by AtulKumar4** [comment]
> Changing vocab in utils/keys.txt (Add Ñ or what you want based on your language) and retrain the model

Thanks
