### ISSUE TITLE
During training, entities are disappearing in the training metrics

### ISSUE THREAD

**Issue by sophiajwchoi** [wenwenyu/PICK-pytorch#9]
Hi, I have the following entities I want to extract. During the training, some entities are not shown in the table and keep disappearing. When I restart the training process, the number of entities shown in the metric table is also different. It gives me an inconsistent result. Do you know what I can do to fix it? 

Entities_list = [
    "invoice_date",
    "tax_rate",
    "subtotal",
    "total"
]
For example,

+--------------+-------+-------+-------+-------+
| name         |   mEP |   mER |   mEF |   mEA |
+==============+=======+=======+=======+=======+
| total        |     0 |     0 |     0 |     0 |
+--------------+-------+-------+-------+-------+
| invoice_date |     0 |     0 |     0 |     0 |
+--------------+-------+-------+-------+-------+
| overall      |     0 |     0 |     0 |     0 |
+--------------+-------+-------+-------+-------+

+--------------+-------+-------+-------+-------+
| name         |   mEP |   mER |   mEF |   mEA |
+==============+=======+=======+=======+=======+
| invoice_date |     0 |     0 |     0 |     0 |
+--------------+-------+-------+-------+-------+
| overall      |     0 |     0 |     0 |     0 |

**Comment by wenwenyu** [comment]
@sophiajwchoi One possible reason is that your train batch data don't contain the entity label provided in `Entities_list`. Make sure the input data has the corresponding entity value. Hope it can help you.
